package mitoitus.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static mitoitus.Kaapelimitoitus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.06.09 11:05:06 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KaapelimitoitusTest {



  // Generated by ComTest BEGIN
  /** testHaeSarake44 */
  @Test
  public void testHaeSarake44() {    // Kaapelimitoitus: 44
    assertEquals("From: Kaapelimitoitus line: 46", 666, haeSarake(0), 0.01); 
    assertEquals("From: Kaapelimitoitus line: 47", 1, haeSarake(1), 0.01); 
    assertEquals("From: Kaapelimitoitus line: 48", 0, haeSarake(1.1), 0.01); 
    assertEquals("From: Kaapelimitoitus line: 49", 666, haeSarake(0.05), 0.01); 
    assertEquals("From: Kaapelimitoitus line: 50", 666, haeSarake(-1.0), 0.01); 
    assertEquals("From: Kaapelimitoitus line: 51", 666, haeSarake(0.5), 0.01); 
    assertEquals("From: Kaapelimitoitus line: 52", 2, haeSarake(0.9), 0.01); 
    assertEquals("From: Kaapelimitoitus line: 53", 1, haeSarake(1.0), 0.01); 
    assertEquals("From: Kaapelimitoitus line: 54", 3, haeSarake(0.8), 0.01); 
    assertEquals("From: Kaapelimitoitus line: 55", 4, haeSarake(0.7), 0.01); 
    assertEquals("From: Kaapelimitoitus line: 56", 5, haeSarake(0.6), 0.01); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHaeArvo78 */
  @Test
  public void testHaeArvo78() {    // Kaapelimitoitus: 78
    String[][] t  = { { "1","2","3","4"} ,{ "2","0","6","1"} } ; 
    String[][] t2 = { { "-2", "koira", "4/10", ""} ,{ "!", "2203-34", "1.5", "-"} ,{ "V", "352", " ", "25/16"} } ; 
    assertEquals("From: Kaapelimitoitus line: 81", "1", haeArvo(t, 1, 3)); 
    assertEquals("From: Kaapelimitoitus line: 82", "1", haeArvo(t, 0, 0)); 
    assertEquals("From: Kaapelimitoitus line: 83", "Taulukko ei kelpaa", haeArvo(null, 2,4)); 
    assertEquals("From: Kaapelimitoitus line: 84", "25/16", haeArvo(t2, 2, 3)); 
    assertEquals("From: Kaapelimitoitus line: 85", "-2", haeArvo(t2, 0, 0)); 
    assertEquals("From: Kaapelimitoitus line: 86", "-", haeArvo(t2, 1, 3)); 
    assertEquals("From: Kaapelimitoitus line: 87", " ", haeArvo(t2, 2, 2)); 
    assertEquals("From: Kaapelimitoitus line: 88", "", haeArvo(t2, 0, 3)); 
    assertEquals("From: Kaapelimitoitus line: 89", "Ei löydy", haeArvo(t2, 9, 9)); 
    assertEquals("From: Kaapelimitoitus line: 90", "Rivi tai sarake ei kelpaa", haeArvo(t2, -1,-1)); 
  } // Generated by ComTest END
}