package mitoitus.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static mitoitus.Kaapelimitoitus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.03.09 14:39:17 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KaapelimitoitusTest {



  // Generated by ComTest BEGIN
  /** testHaeArvo111 */
  @Test
  public void testHaeArvo111() {    // Kaapelimitoitus: 111
    String[][] t  = { { "1","2","3","4"} ,{ "2","0","6","1"} } ; 
    String[][] t2 = { { "-2", "koira", "4/10", ""} ,{ "!", "2203-34", "1.5", "-"} ,{ "V", "352", " ", "25/16"} } ; 
    assertEquals("From: Kaapelimitoitus line: 114", "6", haeArvo(t, 2, 3)); 
    assertEquals("From: Kaapelimitoitus line: 115", "0", haeArvo(t, 0, 0)); 
    assertEquals("From: Kaapelimitoitus line: 116", "Taulukko ei kelpaa", haeArvo(null, 2,4)); 
    assertEquals("From: Kaapelimitoitus line: 117", "25/16", haeArvo(t2, 3, 4)); 
    assertEquals("From: Kaapelimitoitus line: 118", "-2", haeArvo(t2, 1, 1)); 
    assertEquals("From: Kaapelimitoitus line: 119", "-", haeArvo(t2, 2, 4)); 
    assertEquals("From: Kaapelimitoitus line: 120", " ", haeArvo(t2, 3, 3)); 
    assertEquals("From: Kaapelimitoitus line: 121", "", haeArvo(t2, 1, 4)); 
    assertEquals("From: Kaapelimitoitus line: 122", "Ei löydy", haeArvo(t2, 9, 9)); 
    assertEquals("From: Kaapelimitoitus line: 123", "Rivi tai sarake ei kelpaa", haeArvo(t2, -1,-1)); 
  } // Generated by ComTest END
}